allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: set this to true or false
overrides:
  '@emnapi/core': ^2.0.0-alpha.3
  '@emnapi/runtime': ^2.0.0-alpha.3
  '@tiptap/core': 3.29.2
  '@tiptap/pm': 3.29.2
  cac: ^6.7.14
  typescript: ~6.0.3
